--Shotguns
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("12","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("16","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("20","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("28","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("410","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("10","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("4","","G", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("2","","G", 0, 1);

--Standard
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17", "Hornet", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17", "Remington Fireball", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Accelerator", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Hornet", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "CHeetah", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".204", "Ruger", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".218", "Bee", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".219", "Zipper", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".220", "Russian", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".220", "Swift", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".221", "Remington Fireball", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22-250", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".222", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".222", "Remington Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".223", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".223", "Winchester Super Short Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".224", "Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".225", "Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".240", "Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".243", "Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".243", "Winchester Super Short Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".244", "H&H Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".244", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25", "Winchester Super Short Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25-06", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25-20", "Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25-35", "Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".250-3000", "Savage", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".257", "Roberts", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".257", "Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".260", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".264", "Winchester Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".270", "Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".270", "Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".270", "Winchester Short Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".280", "Ross", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".280", "Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".284", "Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30", "Carbine", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","Newton", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","RAR", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30-30","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","Remington AR", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","TC", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30-06","Springfield", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30-30","Winchester (.30 WCF)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30-40","Krag (.30 Army)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30-378","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","H&H Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","AAC Blackout (7.62×35mm)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Remington SA Ultra Mag", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Remington Ultra Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Ruger Compact Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Savage", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Winchester Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Winchester Short Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".303","British", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".303","Savage", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".307","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".308","Marlin Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".308","Norma Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".308","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".32","Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".32","Winchester Self-Loading", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".32","Winchester Special", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".32-20","Winchester (.32 WCF, .32-20 Marlin, .32 Colt Lightning)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".32-40","Ballard", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".32-40","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".325","Winchester Short Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".333","Jeffery Flanged", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Edge", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Federal", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Lapua Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Marlin express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Norma Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Remington Ultra Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Ruger Compact Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Winchester Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338-06","A-Square", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338-378","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".340","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".348","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".35","Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".35","Whelen", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".35","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".35","Winchester Self-Loading", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".350","Remington Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".351","Winchester Self-Loading", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".356","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".358","Norma Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".358","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","H&H Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","Remington Ultra Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","Ruger", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","Whelen (.375-06)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".376","Steyr", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".378","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".38-40","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".38-55","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".38-90","Winchester Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".38-44","UMC", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".40-454","JDJ", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".44-40","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".45-70","Government", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".400","H&H Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".400","Jeffery Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".401","Winchester Self-Loading", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".404","Jeffery", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".405","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".408","CheyTac", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".416","Barrett", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".416","Remington Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".416","Rigby", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".416","Ruger", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".416","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".444","Marlin", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".450/400","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".450","Bushmaster", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".450","Marlin", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".450","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".450","Rigby", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".458x2","American", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".458","Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".458","Lott", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".458","Sabi", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".458","SOCOM", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".458","Winchester Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".460","Weatherby Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".460","Steyr", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".465","H&H Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".470","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".476","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50","Alaskan", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50","Beowulf", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50","BMG", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50","Peacekeeper", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50-70","Government", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50-90","Sharps", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50-110","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50-140","Sharps", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500","Black Powder Express", "I", 1, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500","Jeffery", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500","Nitro Express 3", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500","Nitro Express for black powder 3", "I", 1, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500","No. 2 Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500/450","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500/465","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".505","Gibbs", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".505","Jeffery", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".510","DTC Europ", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".510","Whisper", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".577","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".577","Snider", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".577","Tyrannosaur (.577 T-Rex)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".577/450","Martini-Henry", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".577/.500","Magnum Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".585","Nyati", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".600","Nitro Express", "I", 1, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".600","Overkill", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".700","Nitro Express", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".70-150","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".950","JDJ", "I", 0, 1);

--rim fire
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17", "Hornady Mach 2 (.17HM2)", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17", "Hornady Magnum Rimfire (.17HMR)", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17", "Winchester Super Magnum", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "BB Cap", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Extra Long", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Long", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Long Rifle", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Short", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Winchester Magnum Rimfire (.22 WMR)", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22", "Winchester Rimfire (.22 WRF)", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25", "Stevens", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".32", "Rimfire (.32 Short and .32 Long)", "I", 0, 0);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5mm", "Remington Rimfire Magnum", "M", 0, 0);

--metric
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("4.6x30mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("4.85x49mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("4.92x34mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.45x39mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.56×30mm","MINSAS", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.56x45mm","NATO", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.6x50mm","Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.6x50mm","R Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.6 x 52R", "(.22 Savage Hi-Power)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.6x57mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.6x57mm","R", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.6 x 61","SE (5.6 x 61 Vom Hofe Super Express)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.6 x 61","R SE (5.6 x 61 R Vom Hofe Super Express)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.7mm","Johnson", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.7x28mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5.8x42mm","DBP87", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6 x 35mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","Lee Navy", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm", "AR", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","BR Remington", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","Musgrave", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","TCU", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","PPC", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm-284","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6x45mm","A.K.A. (6mm-223 Remington)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6x47mm","A.K.A. (6mm-222 Rem. Magnum)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","Remington (.244 Remington)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm-250", "A.K.A. (6mmInternational) Walker Version", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5mm","TCU", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5mm", "Creedmoor", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5mm","Grendel", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5mm","Remington Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5-06","A-Square", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5mm/06","A.K.A. 256/06", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5-284", "Norma", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm/30-30", "Improved", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x42mm","Multi-Purpose Cartride (SSK Industries)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x47mm","Lapua", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x50mm","Arisaka", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x52mm","Mannlicher-Carcano", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x52R","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x53mm", "Mannlicher", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x54mm","Mannlicher-Schoenauer", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x55mm","(Also 6.5x55 Swedish Mauser, 6.5 x 55 Mauser)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x57mm","Mauser", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x68mm","(also known as the 6.5 x 68 RWS, 6.5 x 68 Schüler or the 6.5 x 68 Von Hofe Express)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.8mm","Remington SPC", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Shooting Times Easterner (7mm STE)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","International Rimmed", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","TCU A.K.A. (25 Ugalde)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","BR Remington", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","IHMSA", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Dakota", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Gibbs", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Remington Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","RSAUM (Remington Short-Action Ultra Mag)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Remington Ultra Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","STE (Shooting Times Easterner)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","STW (Shooting Times Westerner)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Weatherby Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","WSM (Winchester Short Magnum)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm-06", "Mashburn", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm-06", "", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm-08", "Remington", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm-300", "Weatherby Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7-30", "Waters", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.2","SLEC (7.2 SPECIAL LAW ENFORCEMENT CARTRIDGE)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.21", "Firebird", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.21", "Tomahawk", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.44mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x33mm","Sako", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7×54mm","Finnish", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7×54mm","Fournier", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x57mm","Mauser (.275 Rigby)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x61mm","Sharpe & Hart", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x64mm","Brenneke", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x65mm","R Brenneke", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x66mm","Super Express vom Hofe", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x72", "Rimmed", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x75mm","R Super Express vom Hofe", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.35x51mm","Carcano", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.5x55mm","Schmidt Rubin", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.5x57mm","MAS mod. 1924 7.5x54mm MAS mod. 1929", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62x25mm","Tokarev", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62x38mm", "","M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62×35mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62x39mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62x40", "Wilson Tactical", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62x45mm","vz. 52", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62×51mm","NATO", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62x53mm","Rimmed", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62 x 54R", "(rimmed) (7.62 Russian)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.63x25mm","Mauser", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.65x22mm","Parabellum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.65x53mm","Argentine (7.65x53mm Mauser)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.65x53mm", "","M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.63x54mm","Greek Mannlicher-Schoenauer", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.7x58mm","Arisaka", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.8", "SLEC (( 7.8 SPECIAL LAW ENFORCEMENT CARTRIDGE))", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.82", "Patriot", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.82", "Warbird", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.92x33mm","Kurz", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.92x36mm","EPK", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.92x57mm","Mauser (8mm Mauser or 8x57 JS)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8mm-06","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8mm","Mauser", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8mm","Lebel or 8x50R Lebel", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8mm","Remington Magnum", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x35mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x50mm","Mannlicher", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x56mm","Mannlicher-Schoenauer", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x56mm", "R Steyr or Hungarian", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x58mm","RD (rimmed danish)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x60mm","S", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x64mm","S Brenneke", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8x68mm","S", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9x39mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9x45mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9x53mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9x56mm","Mannlicher-Schoenauer", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9x57mm","Mauser", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x57mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x62mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x64mm","Brenneke", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x65Rmm","Brenneke", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x65mm","Collath", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x66mm","Sako", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x72mm","D", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.3x74mm","R", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("9.5x57mm","Mannlicher-Schoenauer (.375 Rimless Nitro Express x 2-1/4)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("10.75x57mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("10.75x68mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("10.75x73mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("11x60mm","Mauser", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("12.7mm","British No. 2", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("12.7x99mm","NATO (Multi-Purpose)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("12.7x54mm","(subsonic)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("12.7x108mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("13x64B", "","M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("13.2x92mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("14.5x114mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("14.5mm","JDJ", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("15.2mm","Steyr Armor Piercing Fin Stabilized Discarding Sabot (APFSDS)", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("20mm","caliber", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("20x110mm","USN", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("23x115mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("23x152mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("25x137mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("30x165mm","", "M",0,1);
INSERT INTO caliber (caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("30x173mm","", "M",0,1);

--obscure standard
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".14","Walker Hornet", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".14/221","", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".14-222", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17", "Ackley Bee", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17","CCM", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17","Mach IV", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17","PMC/Aguila", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17","PPC", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17-06", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17-222", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17-223", "", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17-225", "Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17/23", "SMC", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".17-357", "RG (.172 Wildcat based on the 357 SIG)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".191", "(4.85mm SAA)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".19","Badger", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".19","Calhoon Hornet", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".19-223", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("20","BR", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("20","Fergusson Ace", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("20","Magna", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("20","PPC", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".20","Tactical", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".20","VarTarg", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".20-06", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".218","Mashburn Bee", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".219","Donaldson Wasp", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","BR Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","Cheetah", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","Eargesplitten Loudenboomer", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","K Hornet", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","Newton", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","PPC", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","Savage High Power", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","Spitfire", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","Super Jet", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","Waldog", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22","WCF", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22-06", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22-15-60","Stevens", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22-243","Middlestead", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22-284","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22/30","(T65 Duplex)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22/30-30","Improved", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".22/303", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".220","Weatherby Rocket", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".222","Rimmed", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".223","AI", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".224","Donaldson Ace", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".240","Apex (.240 Belted Nitro Express and .240 Magnum Flanged)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25","Ackley Krag", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25","Gibbs", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25","Krag", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25","Remington", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25-21","Stevens", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25-25","Stevens", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".256","Newton", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".256","Winchester Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".264","LBC-AR", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".264","warrior magnum (6.5x40 mm)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".25/303", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".270","Titus Savage", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".275","H&H Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".280","British", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".276","Enfield", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".276","Pedersen", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".280","Ross", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","BR", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","USA", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30","Walker", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30-03", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".309","jdj", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".30-06","JDJ", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".309","Bull", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Dakota", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","ICL Grizzly", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Lapua Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Remington American Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300","Whisper (.300 Fireball)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".300-221", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".303-06", "","I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".330","Dakota", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".333","Jeffery Flanged", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".333","OKH", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338-06","A-Square", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Hawk/Scoville", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Whisper", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338","Voschol", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".338x 57","O'Connor", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".35","Samba (Also .35 WSM)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".357/.44","B & D (Bain and Davis)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","Dakota", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375","Whisper", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".375 H&H","(based on full length 375 Ruger)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".40-65","Winchester", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".40-70","Sharps", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".400","Whelen", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".416","Taylor", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".416","Whisper", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("416","(based on full length 375 Ruger)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".425","Westley Richards", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".44","Henry", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".44","WSP", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".45-90","Sharps", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".45-110","Sharps", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".45-120","Sharps", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".450","Watts Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("450","(2.598 404 Case)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("460","(2.850 404 Case)", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".458","SOCOM", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".470","Capstick", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".475","OKH", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".475","Ackley", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".50","Razor Back", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".500","Phantom", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".550","Magnum", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".600/577","REWA", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".700","AHR", "I", 0, 1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES (".700","WTF", "I", 0, 1);

--obscure metric
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("4.5mm","mkr", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5mm","Craig", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("5mm/35","SMc", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6-06", "","M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6-284", "","M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","AR" ,"M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","BRX", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","Dasher", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6mm","XC", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6x45mm", "","M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6 x 47","Swiss Match (6mm/222 Mag)", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5-06", "","M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5","Grendel (6.5x39mm)", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5","CSS", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5","PPCX", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5","BPC", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5","BR", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5x40mm","(.264 warrior magnum)", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5 x 47","Lapua", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5 x 57", "","M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5","Jonson", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5","Wby Mag", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("6.5/.243","WSSM", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Dakota", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7mm","Gradle Express", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7x54mm","Fournier", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62","Jonson", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.62","Thumper", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.82","Lazzeroni Patriot", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("7.82","Lazzeroni Warbird", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("8mm-06","Ackley Improved", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("10,4 x 38","Vetterli (US: .41 Swiss)", "M",0,1);
INSERT INTO caliber(caliber_number, manufacturer, unit, isBlackPowder, isCenterFire) VALUES ("10,4 x 47","Italian Vetterli", "M",0,1);