INSERT INTO Action (action) VALUES ('Pump-action');
INSERT INTO BarrelLength (barrellength) VALUES ('18 in (460 mm) to 30 in (760 mm)');
INSERT INTO Caliber (caliber) VALUES ('.410 bore');
INSERT INTO Caliber (caliber) VALUES ('12 gauge');
INSERT INTO Caliber (caliber) VALUES ('16 gauge');
INSERT INTO Caliber (caliber) VALUES ('20 gauge');
INSERT INTO Caliber (caliber) VALUES ('28 gauge');
INSERT INTO Country (country) VALUES ('United States');
INSERT INTO FeedSystem (feedsystem) VALUES ('4+1 to 7+1 round internal tube magazine');
INSERT INTO Length (length) VALUES ('37.25 in (946 mm) to 50.5 in (1,280 mm)');
INSERT INTO Manufacturer (manufacturer) VALUES ('Remington Arms');
INSERT INTO MuzzleVelocity (muzzlevelocity) VALUES ('');
INSERT INTO Produced (produced) VALUES ('1951–present');
INSERT INTO Sights (sights) VALUES ('Also cantilever and receiver-mounts for scopes');
INSERT INTO Sights (sights) VALUES ('Bead');
INSERT INTO Sights (sights) VALUES ('adjustable open sights');
INSERT INTO Sights (sights) VALUES ('ghost ring');
INSERT INTO Sights (sights) VALUES ('twin bead');
INSERT INTO Type (type) VALUES ('Shotgun');
INSERT INTO Variant (variant) VALUES ('Express');
INSERT INTO Variant (variant) VALUES ('MCS');
INSERT INTO Variant (variant) VALUES ('Marine');
INSERT INTO Variant (variant) VALUES ('SPS');
INSERT INTO Variant (variant) VALUES ('SPS-T');
INSERT INTO Variant (variant) VALUES ('Super Mag');
INSERT INTO Variant (variant) VALUES ('TAC');
INSERT INTO Variant (variant) VALUES ('Wingmaster');
INSERT INTO Variant (variant) VALUES ('XCS');
INSERT INTO Weapon (weapon,info,image) VALUES ('Remington 870', 'A very popular gun', 'rem870.jpeg');
INSERT INTO Weight (weight) VALUES ('');
INSERT INTO WeaponAction (weapon_id, action_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Action WHERE Action = 'Pump-action'));
INSERT INTO WeaponBarrelLength (weapon_id, barrellength_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM BarrelLength WHERE BarrelLength = '18 in (460 mm) to 30 in (760 mm)'));
INSERT INTO WeaponCaliber (weapon_id, caliber_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Caliber WHERE Caliber = '.410 bore'));
INSERT INTO WeaponCaliber (weapon_id, caliber_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Caliber WHERE Caliber = '12 gauge'));
INSERT INTO WeaponCaliber (weapon_id, caliber_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Caliber WHERE Caliber = '16 gauge'));
INSERT INTO WeaponCaliber (weapon_id, caliber_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Caliber WHERE Caliber = '20 gauge'));
INSERT INTO WeaponCaliber (weapon_id, caliber_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Caliber WHERE Caliber = '28 gauge'));
INSERT INTO WeaponCountry (weapon_id, country_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Country WHERE Country = 'United States'));
INSERT INTO WeaponFeedSystem (weapon_id, feedsystem_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM FeedSystem WHERE FeedSystem = '4+1 to 7+1 round internal tube magazine'));
INSERT INTO WeaponLength (weapon_id, length_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Length WHERE Length = '37.25 in (946 mm) to 50.5 in (1,280 mm)'));
INSERT INTO WeaponManufacturer (weapon_id, manufacturer_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Manufacturer WHERE Manufacturer = 'Remington Arms'));
INSERT INTO WeaponMuzzleVelocity (weapon_id, muzzlevelocity_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM MuzzleVelocity WHERE MuzzleVelocity = ''));
INSERT INTO WeaponProduced (weapon_id, produced_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Produced WHERE Produced = '1951–present'));
INSERT INTO WeaponSights (weapon_id, sights_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Sights WHERE Sights = 'Also cantilever and receiver-mounts for scopes'));
INSERT INTO WeaponSights (weapon_id, sights_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Sights WHERE Sights = 'Bead'));
INSERT INTO WeaponSights (weapon_id, sights_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Sights WHERE Sights = 'adjustable open sights'));
INSERT INTO WeaponSights (weapon_id, sights_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Sights WHERE Sights = 'ghost ring'));
INSERT INTO WeaponSights (weapon_id, sights_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Sights WHERE Sights = 'twin bead'));
INSERT INTO WeaponType (weapon_id, type_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Type WHERE Type = 'Shotgun'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'Express'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'MCS'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'Marine'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'SPS'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'SPS-T'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'Super Mag'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'TAC'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'Wingmaster'));
INSERT INTO WeaponVariant (weapon_id, variant_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Variant WHERE Variant = 'XCS'));
INSERT INTO WeaponWeight (weapon_id, weight_id) VALUES ((SELECT id FROM Weapon WHERE weapon = 'Remington 870'), (SELECT id FROM Weight WHERE Weight = ''));
